create table itens (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  titulo text not null,
  categoria text not null, -- 'Livro', 'Série', 'Música', 'Pintura', etc.
  descricao text,
  imagem_url text, -- Link para capa ou imagem ilustrativa
  link_externo text
);

-- Ativar Read para todo mundo (anônimo) e Write apenas para você se quiser autenticar depois.
-- Para simplificar o mural público, vamos liberar o acesso de leitura:
alter table itens enable row level security;
create policy "Permitir leitura pública" on itens for select using (true);
